#include "Commands/attack.h"
#include "Commands/recruit.h"
#include "Commands/move.h"
#include "Commands/printinfo.h"
#include "Commands/printmap.h"
#include "Commands/changeunit.h"
#include "Commands/end_turn.h"
#include "Commands/undo.h"